name: Prepare next release üöÄ

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run release draft to extract labels ‚òïÔ∏è
    runs-on: ubuntu-latest
    steps:
      - name: Run release draft to extract labels ‚òïÔ∏è
        uses: tchoupinax/repo-config/shared-actions/steps/dx/prepare-draft-release@v0
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}

  docker:
    name: Build intermediate container üê≥
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%Hh%M')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tchoupinax/fuzzy-engine
          flavor: latest=true
          tags: |
            type=raw,value=latest-${{ steps.date.outputs.date }}

      - name: Build intermediate container üê≥
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
